Enable `-c` (count-allocations) in `run-problem`.
Signed-off-by: Savio Sena <savio.sena@gmail.com>

diff --git a/bin/run-problem b/bin/run-problem
--- a/bin/run-problem
+++ b/bin/run-problem
@@ -7,19 +7,22 @@
 target_dir=src/bin
 
 if [ ! -d "./$target_dir" ]; then
-   printf "error: you must run this script from the root of the repository.\n" >&2
-   exit 2
- fi
+    printf "error: you must run this script from the root of the repository.\n" >&2
+    exit 2
+fi
 
-# TODO allow multiple tests cases arguments.
+if [ "$1" = "-c" ]; then
+    shift
+    EXTRA_ARGS="--features=count-allocations"
+fi
 
-if [ $# -lt 1 ] || [ $# -gt 2  ]; then
-   printf "Usage: %s <problem-name> [test-case]\n" "$(basename $0)" >&2
-   exit 1
+if [ $# -lt 1 ] || [ $# -gt 2 ]; then
+    printf "Usage: %s [-c] <problem-name> [test-case]\n" "$(basename $0)" >&2
+    exit 1
 fi
 
 problem_name="$1"
-test_case="$2"
+shift
 
 mkdir -p output/$problem_name
 
@@ -27,26 +30,29 @@ run_problem() {
     input_file=$1
     output_file=$2
 
-    printf "running: %s < %s\n" "$problem_name" "$(basename $input_file)" >&2
+    printf "running: %s < %s > %s\n" \
+        "$problem_name" \
+        "$(basename $input_file)" \
+        "$(basename $output_file)" >&2
 
-    cargo build -q --bin $problem_name &&
-        ./target/debug/$problem_name < $input_file |
-            tee $output_file
+    cargo run -q $EXTRA_ARGS --bin $problem_name < "$input_file" | \
+        tee "$output_file"
 }
 
-if [ -z "$test_case" ]; then
+if [ "$#" -eq "0" ]; then
     for input_file in "input/$problem_name"/*; do
         run_problem "$input_file" "output/$problem_name/$(basename $input_file)"
     done
-    
 else
-    input_file="input/$problem_name/${test_case}.txt"
-    output_file="output/$problem_name/${test_case}.txt"
+    for test_case in "$@"; do
+        input_file="input/$problem_name/${test_case}.txt"
+        output_file="output/$problem_name/${test_case}.txt"
 
-    if [ ! -f $input_file ]; then
-        printf "error: file not found: %s.\n" "$input_file" >&2
-        exit 3
-    fi
+        if [ ! -f $input_file ]; then
+            printf "error: file not found: %s.\n" "$input_file" >&2
+            exit 3
+        fi
 
-    run_problem "$input_file" "$output_file" 
+        run_problem "$input_file" "$output_file"
+    done
 fi
